import { StyleSheet } from "react-native";

export const style = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.7)",
  },
  modalTitulo: {
    alignSelf: "flex-start",
    left: 16,
    bottom: 5,
    fontSize: 16,
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  containerPopUP: {
    justifyContent: "center",
    alignItems: "center",
    alignContent: "center",
    width: "100%",
    height: "20%",
    borderRadius: 30,
    backgroundColor: "white",
    flexDirection: "column",
  },
  containerBotao: {
    flex: 1,
    width: "80%",
    flexDirection: "row",
    marginBottom: "2%",
    marginTop: "4%",
    justifyContent: "space-between",
  },
  botao: {
    alignItems: "center",
    width: "80%",
    height: "80%",
    backgroundColor: "#6495ED",
    justifyContent: "center",
    borderRadius: 15,
  },
  umBotao: {
    width: "45%",
    alignItems: "center",
    height: "100%",
    justifyContent: "center",
    borderRadius: 15,
  },
  containerTit: {
    flex: 1,
    marginTop: "5%",
    alignContent: "center",
    justifyContent: "center",
    width: "90%",
    textAlign: "center",
    fontWeight: "bold",
    color: "black",
  },
  tit: {
    textAlign: "center",
    fontWeight: "bold",
    color: "black",
    fontSize: 18,
  },
  containerTex: {
    flex: 0.5,
    marginTop: "3%",
    textAlign: "center",
    fontWeight: "400",
    color: "#7A7A7A",
  },
  tex: {
    textAlign: "center",
    fontWeight: "400",
    color: "gray",
    fontSize: 14,
  },
  bText: {
    textAlign: "center",
    fontWeight: "500",
    color: "white",
  },
  input: {
    width: "100%",
    height: 50,
    borderColor: "black",
    borderWidth: 1,
    borderRadius: 15,
    paddingStart: 16,
    fontSize: 17,
    marginBottom: 15,
  },
  modalView: {
    margin: 20,
    width: "85%",
    backgroundColor: "white",
    borderRadius: 20,
    padding: 10,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  scrollModal: {
    width: "100%",
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: "#F194FF",
  },
  buttonClose: {
    backgroundColor: "#2196F3",
    alignSelf: "center",
    width: "40%",
    marginBottom: 10,
  },
  textStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center",
  },
  botaoCancelar: {
    height: "30%",
    width: "30%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "red",
    borderRadius: 50,
    marginBottom: 5,
  },
  TextoBotaoCancelar: {
    color: "white",
  },
});
export default style;
